### ISSUE TITLE
Segmentation faults in mime handling

### ISSUE THREAD

**Issue by rwhitworth** [dinhviethoa/libetpan#274]
Hello,
I was using American Fuzzy Lop (afl-fuzz) to fuzz input to the mime-parse test program. Is fixing these crashes something you're interested in? The input files can be found here: https://github.com/rwhitworth/libetpan-fuzz/.

The files can be executed as `./mime-parse id_filename` to cause seg faults.

Let me know if I can provide any more information to help narrow down this issue.

**Comment by dinhviethoa** [comment]
Thanks! I'm interested in the fixes of the crashes.
If you have some pull requests, it would be awesome.
If not, I'll take a look later.

**Comment by rwhitworth** [comment]
Sorry @dinhviethoa my C debugging skills aren't so great, so I probably won't be much help with a PR, but I would be glad to re-test and fuzz any solutions

**Comment by pmetzger** [comment]
On Fri, 28 Apr 2017 09:16:35 -0700 Hoà V. DINH
<notifications@github.com> wrote:
> Thanks! I'm interested in the fixes of the crashes.
> If you have some pull requests, it would be awesome.
> If not, I'll take a look later.
> 
> 

Just to note: segfaults of this sort probably mean an exploitable
security vulnerability. This is probably worth looking at sooner
rather than later...

-- 
Perry E. Metzger		perry@piermont.com

**Comment by pmetzger** [comment]
Hi! Not to be alarmist, but it is probably quite dangerous for all the users of libetpan to have publicly disclosed unpatched vulnerabilities out in the wild, especially given that they're probably remotely exploitable. Given that it is far too late to not disclose them in public, perhaps some priority could be given to patching? I will volunteer to help get a CVE number for these if you need that assistance.

**Comment by ticho** [comment]
Looks like all of the test files make mime-parse croak because of the same bug in parsing header lines.

Attached patch (renamed to .txt, because Github is retarded and doesn't allow attaching files with .patch suffix) contains a possible fix.

What happens is that when mailimf_group_parse() parses a header line containing list of addresses (e.g. "Cc"), it sometimes fails, and by the time it gets to calling mailimf_group_new(display_name, mailbox_list), the pointer mailbox_list is still pointing to NULL. The code doesn't check for this outcome.

The patch just adds a check for this to the beginning of mailimf_group_new(). I *think* it's the right thing to do, but @dinhviethoa is the best person to judge that, being more familiar with the mailimf code. Anyway, this prevents the segfaults from all @rwhitworth 's test cases, and still seems to parse all "normal" message files I tried throwing at it.

[issue274-possible-fix.patch.txt](https://github.com/dinhviethoa/libetpan/files/981925/issue274-possible-fix.patch.txt)

**Comment by pmetzger** [comment]
@ticho As a user of the library, thank you so much!

**Comment by dinhviethoa** [comment]
Thanks! I fixed the issue.

**Comment by pmetzger** [comment]
Should we get a CVE for it? It probably deserves one.

**Comment by dinhviethoa** [comment]
@pmetzger I don't know what's the process CVE. Would you be able to take care of it?
Thanks!

**Comment by pmetzger** [comment]
I will happily do so. Let me know when there's a point release so that I can name that as the fix for the issue.

**Comment by pmetzger** [comment]
For those watching this issue, it has been assigned  CVE-2017-8825 and libetpan 1.8 fixes the bug.
